[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "batch-invariant-ops"
version = "0.1.0"
description = "Triton-based batch-invariant operations for PyTorch"
authors = [
    {name = "Horace", email = "horace@example.com"}
]
requires-python = ">=3.8"
dependencies = [
    "torch>=2.9.0",
    "triton",
    "transformers",
    "rich",
    "accelerate",
    "vllm @ git+https://github.com/Chillee/vllm.git@main",
]
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Topic :: Scientific/Engineering :: Artificial Intelligence",
]

[project.optional-dependencies]
dev = [
    "pytest",
    "black",
    "isort",
    "flake8"
]

[tool.setuptools.packages.find]
where = ["."]
include = ["batch_invariant_ops*"]

[tool.black]
line-length = 100
target-version = ['py38']

[tool.isort]
profile = "black"
line_length = 100